language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/trackingCoins
  DELPOY_PATH: $APP_PATH/trackingCoinsRails1

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_a2e211adead8_key -iv $encrypted_a2e211adead8_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: false

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    rsync --recursive ./* $SSH_USER@$SSH_HOST:$DELPOY_PATH/'
    && ssh root@$SSH_HOST "docker-compose run app bash -c \"bundle install --check || bundle exec rails db:migrate \" && systemctl restart coins"'
  on:
    branch: master
