version: '3.6'
services:
  db:
    image: postgres:10.3-alpine
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - coins-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
  redis:
      image: redis:4.0.9-alpine
      command: redis-server --requirepass $REDIS_PASSWORD
      ports:
        - $REDIS_PORT:$REDIS_PORT
      volumes:
        - coins-redis:/var/lib/redis/data

  app:
    build: .
    command: >
      bash -c "
      bundle check
      || bundle install --clean
      && rm -f tmp/pids/server.pid
      && bundle exec rails db:migrate
      && bundle exec rails server"
    ports:
      - $PORT:$PORT
    volumes:
      - .:/coins
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?pool=$POSTGRES_POOL
      REDIS_PROVIDER: redis://:$REDIS_PASSWORD@$REDIS_HOST:$REDIS_PORT?db=$REDIS_DB
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/coins
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?pool=$POSTGRES_POOL
      REDIS_PROVIDER: redis://:$REDIS_PASSWORD@$REDIS_HOST:$REDIS_PORT?db=$REDIS_DB
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site:/var/www/coins
      - ./site/letsencrypt:/etc/nginx/ssl/coins
    ports:
      - 8090:8090
      - 80:80
      - 443:44'
volumes:
  coins-postgres:
  coins-redis:
