version: '3.6'
services:
  db:
    image: postgres:10.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - coins-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 6k3vddrb2v
  redis:
      image: redis:4.0.9-alpine
      ports:
        - '6379:6379'
      volumes:
        - coins-redis:/var/lib/redis/data
  app:
    build: .
    command: >
      bash -c "
      bundle check
      || bundle install --clean
      && rm -f tmp/pids/server.pid
      && bundle exec rails db:migrate
      && bundle exec rails server"
    ports:
      - '8080:8080'
    volumes:
      - .:/coins
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/coins
    env_file:
      - .env
    depends_on:
      - redis
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site:/var/www/coins
      - ./site/letsencrypt:/etc/nginx/ssl/coins
    ports:
      - '8090:8090'
      - '80:80'
      - '443:443'
volumes:
  coins-postgres:
  coins-redis:
