version: '3.6'
services:
  db:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - coins-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 6k3vddrb2v
  redis:
      image: redis:4.0.9-alpine
      ports:
        - '6379:6379'
      volumes:
        - coins-redis:/var/lib/redis/data:rw
  web:
    build: .
    command: >
      bash -c "
      bundle check
      || bundle install --clean
      && rm -f tmp/pids/server.pid
      && rails db:migrate
      && rails server"
    volumes:
      - .:/coins
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      - db
      - redis
    stdin_open: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/coins
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  coins-postgres:
  coins-redis:
