default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  database: <%= ENV['PGDATABASE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
